import { FlatList,RefreshControl,StyleSheet,Text,View } from 'react-native';
import { useLocalSearchParams,router } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { api } from '@/services/api';
import { Card,ScreenTitle,StateView,Badge } from '@/components/ui';
import { colors,space } from '@/theme';

const config:Record<string,{title:string;endpoint:string;icon:keyof typeof Ionicons.glyphMap}>={
 timetable:{title:'Weekly timetable',endpoint:'/timetable',icon:'calendar-outline'}, attendance:{title:'Attendance',endpoint:'/attendance',icon:'checkmark-done-outline'}, homework:{title:'Homework',endpoint:'/assignments',icon:'reader-outline'}, fees:{title:'Fees & payments',endpoint:'/fees',icon:'wallet-outline'}, students:{title:'Students',endpoint:'/students',icon:'people-outline'}, classes:{title:'Classes & subjects',endpoint:'/classes',icon:'school-outline'}
};
const text=(x:any)=>x?.title||x?.label||x?.admissionNo||x?.name||x?.schoolClass?.name||'School record';
const sub=(x:any)=>x?.description||x?.body||x?.status||x?.dueAt&&`Due ${new Date(x.dueAt).toLocaleDateString()}`||x?.section&&`${x.section.schoolClass?.name||''} · Section ${x.section.name}`||'Tap for details';
export default function Module(){const {name}=useLocalSearchParams<{name:string}>();const c=config[name||''];const q=useQuery({queryKey:['module',name],queryFn:async()=>{const r=await api.get(c.endpoint);return Array.isArray(r.data.data)?r.data.data:[]},enabled:!!c});if(!c)return <StateView title="Module not found" body="This school module is not available yet."/>;if(q.isLoading)return <StateView loading title={`Opening ${c.title}`} body="Preparing the latest records…"/>;if(q.isError)return <View style={s.page}><StateView icon="cloud-offline-outline" title="Couldn’t load this" body="Check your connection, then pull down to try again."/></View>;return <FlatList style={s.page} contentContainerStyle={s.content} data={q.data} keyExtractor={(x:any,i)=>x.id||String(i)} refreshControl={<RefreshControl refreshing={q.isFetching} onRefresh={q.refetch}/>} ListHeaderComponent={<View style={s.header}><Text onPress={()=>router.back()} style={s.back}>‹ Back</Text><ScreenTitle eyebrow="School hub" title={c.title} subtitle="Clear, current and easy to scan."/></View>} ListEmptyComponent={<StateView icon={c.icon} title="Nothing here yet" body="New records will appear here when they’re added."/>} ItemSeparatorComponent={()=><View style={{height:12}}/>} renderItem={({item}:any)=><Card style={s.row}><View style={s.icon}><Ionicons name={c.icon} size={22} color={colors.primary}/></View><View style={{flex:1,gap:5}}><Text style={s.title}>{text(item)}</Text><Text numberOfLines={2} style={s.sub}>{sub(item)}</Text></View>{item.status&&<Badge label={item.status} tone={item.status==='PAID'||item.status==='PRESENT'?'green':item.status==='ABSENT'||item.status==='OVERDUE'?'red':'orange'}/>}</Card>}/>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas},content:{padding:space.xl,paddingTop:54,paddingBottom:50},header:{gap:18,marginBottom:24},back:{fontSize:16,fontWeight:'700',color:colors.primary},row:{flexDirection:'row',alignItems:'center',gap:13},icon:{width:46,height:46,borderRadius:15,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},title:{fontSize:16,fontWeight:'800',color:colors.ink},sub:{fontSize:13,lineHeight:18,color:colors.muted}});
